"""
Post-processes raw Jinja2 render output into clean, standards-compliant CAPL.

Why post-processing?
--------------------
Templates are written by humans and inevitably produce:
- Consecutive blank lines (Jinja whitespace from ``{% if %}`` blocks)
- Trailing whitespace on lines
- Inconsistent indentation around ``{ }`` blocks
- Missing or duplicated file-level includes

The post-processor applies deterministic, mechanical fixes so template
authors don't have to think about whitespace and every output file looks
hand-written.

Design
------
``CAPLPostProcessor.process()`` runs a sequence of ``_Step`` callables
in order.  Each step takes a string and returns a string.  Steps are
composable and independently testable.

Usage
-----
::

    pp = CAPLPostProcessor()
    clean_capl = pp.process(raw_jinja_output, source_hint="rx_check.j2")
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable, Optional

from loguru import logger

# Type alias for a post-processing step function
_Step = Callable[[str], str]

# CAPL include statements the tool always injects if not already present
_STANDARD_INCLUDES: list[str] = [
    # No standard library headers in CAPL — includes are node-specific.
    # Leave this list empty by default; projects can inject via config.
]

# Regex patterns (compiled once)
_TRAILING_WHITESPACE  = re.compile(r"[ \t]+$", re.MULTILINE)
_CONSECUTIVE_BLANKS   = re.compile(r"\n{3,}")          # 3+ newlines → 2
_BLANK_AFTER_OPEN     = re.compile(r"(\{)\s*\n\s*\n")  # blank line after {
_BLANK_BEFORE_CLOSE   = re.compile(r"\n\s*\n(\s*\})")  # blank line before }
_MULTIPLE_SEMICOLONS  = re.compile(r";{2,}")            # ;; artefacts
_CAPL_COMMENT_HEADER  = re.compile(
    r"^/\*.*?CAPL Gen Tool.*?\*/", re.DOTALL | re.MULTILINE
)


# ---------------------------------------------------------------------------
# Post-processor
# ---------------------------------------------------------------------------


@dataclass
class CAPLPostProcessor:
    """
    Cleans and standardises raw Jinja2 render output.

    Parameters
    ----------
    add_file_header:
        Prepend a ``/* Generated by CAPL Gen Tool … */`` comment block
        when none is already present.  Default True.
    ensure_includes:
        Inject any entries from ``required_includes`` that are absent.
        Default True.
    required_includes:
        List of ``#include`` / ``includes`` directives to ensure are present.
        Default: empty (no mandatory includes).
    max_consecutive_blank_lines:
        Collapse runs of blank lines longer than this to this value.  Default 1.
    normalize_indentation:
        Rewrite indentation to use spaces (convert tabs → 2 spaces).  Default True.
    strip_trailing_whitespace:
        Remove trailing spaces/tabs from every line.  Default True.
    """

    add_file_header:              bool       = True
    ensure_includes:              bool       = True
    required_includes:            list[str]  = field(default_factory=list)
    max_consecutive_blank_lines:  int        = 1
    normalize_indentation:        bool       = True
    strip_trailing_whitespace:    bool       = True

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def process(self, raw: str, source_hint: str = "") -> str:
        """
        Run the full post-processing pipeline on *raw* CAPL source.

        Parameters
        ----------
        raw:
            Raw string output from Jinja2 ``template.render()``.
        source_hint:
            Template filename used only in log messages (e.g. ``"rx_check.j2"``).

        Returns
        -------
        str
            Cleaned CAPL source ready to write to a ``.can`` file.
        """
        if not raw or not raw.strip():
            logger.warning(
                f"[PostProcessor] Empty render output"
                + (f" from '{source_hint}'" if source_hint else "")
            )
            return raw

        logger.debug(
            f"[PostProcessor] Processing {len(raw)} chars"
            + (f" ({source_hint})" if source_hint else "")
        )

        steps: list[_Step] = self._build_steps()
        result = raw
        for step in steps:
            result = step(result)

        logger.debug(
            f"[PostProcessor] Done — {len(raw)} → {len(result)} chars"
        )
        return result

    # ------------------------------------------------------------------
    # Step builder
    # ------------------------------------------------------------------

    def _build_steps(self) -> list[_Step]:
        """Return ordered list of post-processing steps to apply."""
        steps: list[_Step] = []

        if self.normalize_indentation:
            steps.append(self._step_normalize_indentation)

        if self.strip_trailing_whitespace:
            steps.append(self._step_strip_trailing_whitespace)

        steps.append(self._step_collapse_blank_lines)
        steps.append(self._step_clean_brace_whitespace)
        steps.append(self._step_fix_double_semicolons)

        if self.ensure_includes and self.required_includes:
            steps.append(self._step_ensure_includes)

        if self.add_file_header:
            steps.append(self._step_add_file_header)

        steps.append(self._step_ensure_final_newline)

        return steps

    # ------------------------------------------------------------------
    # Individual step implementations
    # ------------------------------------------------------------------

    @staticmethod
    def _step_normalize_indentation(src: str) -> str:
        """Convert tabs to 2-space indentation (CAPL convention)."""
        return src.replace("\t", "  ")

    @staticmethod
    def _step_strip_trailing_whitespace(src: str) -> str:
        """Remove trailing spaces/tabs from every line."""
        return _TRAILING_WHITESPACE.sub("", src)

    def _step_collapse_blank_lines(self, src: str) -> str:
        """
        Collapse runs of more than ``max_consecutive_blank_lines`` blank lines.

        Jinja2 ``{% if %}`` / ``{% for %}`` blocks often leave 2–3 blank lines
        where a single blank (or none) is intended.
        """
        replacement = "\n" * (self.max_consecutive_blank_lines + 1)
        return _CONSECUTIVE_BLANKS.sub(replacement, src)

    @staticmethod
    def _step_clean_brace_whitespace(src: str) -> str:
        """
        Remove spurious blank lines immediately inside ``{ }`` blocks.

        Before::
            on message CAN1.0x1A0 {

              variables { ... }

            }

        After::
            on message CAN1.0x1A0 {
              variables { ... }
            }
        """
        src = _BLANK_AFTER_OPEN.sub(r"\1\n", src)
        src = _BLANK_BEFORE_CLOSE.sub(r"\n\1", src)
        return src

    @staticmethod
    def _step_fix_double_semicolons(src: str) -> str:
        """
        Collapse ``;;`` → ``;``.

        Template conditionals can emit a semicolon at the end of a statement
        and the surrounding template may add another.
        """
        return _MULTIPLE_SEMICOLONS.sub(";", src)

    def _step_ensure_includes(self, src: str) -> str:
        """
        Inject any required ``includes`` directives not already present.

        CAPL uses ``includes { … }`` blocks, not C preprocessor ``#include``.
        This step checks for each required include as a substring and prepends
        missing ones near the top of the file.
        """
        if not self.required_includes:
            return src

        missing = [inc for inc in self.required_includes if inc not in src]
        if not missing:
            return src

        inject = "\n".join(missing) + "\n\n"
        logger.debug(
            f"[PostProcessor] Injecting {len(missing)} missing include(s)"
        )
        return inject + src

    @staticmethod
    def _step_add_file_header(src: str) -> str:
        """
        Prepend a ``/* Generated by … */`` banner if none is present.

        Only added when the file does not already start with a CAPL Gen Tool
        header comment (avoids doubling on re-runs).
        """
        if _CAPL_COMMENT_HEADER.search(src):
            return src  # header already present

        import datetime
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        banner = (
            "/*\n"
            " * Generated by CAPL Gen Tool\n"
            f" * {now}\n"
            " *\n"
            " * DO NOT EDIT MANUALLY — re-generate from requirements.xlsx\n"
            " */\n\n"
        )
        return banner + src

    @staticmethod
    def _step_ensure_final_newline(src: str) -> str:
        """Ensure the file ends with exactly one newline."""
        return src.rstrip("\n") + "\n"

    # ------------------------------------------------------------------
    # Convenience: process a dict of renders at once
    # ------------------------------------------------------------------

    def process_all(
        self, renders: dict[str, str]
    ) -> dict[str, str]:
        """
        Process a mapping of ``{requirement_id: raw_capl}`` in one call.

        Returns the same dict structure with cleaned values.
        Errors in individual renders are logged and the original is kept.
        """
        result: dict[str, str] = {}
        for req_id, raw in renders.items():
            try:
                result[req_id] = self.process(raw, source_hint=req_id)
            except Exception as exc:
                logger.warning(
                    f"[PostProcessor] Failed on '{req_id}': {exc} — keeping raw output"
                )
                result[req_id] = raw
        return result